name: CI debug session
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        default: false

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm SSH session
        if: ${{ github.event.inputs.debug_enabled == true }}
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
